FROM maven:3-jdk-8-slim AS BUILDER
WORKDIR /run

COPY ./model/pom.xml /run/model/
RUN ["/bin/bash", "-c", "pushd model && mvn dependency:go-offline && popd"]
COPY ./model /run/model/
RUN ["/bin/bash", "-c", "pushd model && mvn install && popd"]

COPY ./transaction-processor/pom.xml /run/transaction-processor/
RUN ["/bin/bash", "-c", "pushd transaction-processor && mvn dependency:go-offline && popd"]
COPY ./transaction-processor /run/transaction-processor/
RUN ["/bin/bash", "-c", "pushd transaction-processor && mvn install && popd"]

FROM openjdk:8-jre-slim

EXPOSE 8080
COPY --from=BUILDER /run/transaction-processor/target/dependency-jars /run/dependency-jars
COPY --from=BUILDER /run/transaction-processor/target/transaction_processor-1.0-SNAPSHOT.jar /run/application.jar
WORKDIR /run
ENTRYPOINT java -jar application.jar ${VALIDATOR_URI} ${MASTER_STATE_NAME}