version: "2.1"

volumes:
  built-frontend:

services:
  settings-tp:
    logging:
      driver: "none"
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-default
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  voting-tp:
    logging:
        driver: "none"
    build: 
      context: ../transaction-processor
      dockerfile: Dockerfile-tp
    depends_on:
      - validator
    environment:
      VALIDATOR_URI: tcp://validator:4004
      MASTER_STATE_NAME: dev

  voting-api:
    logging:
      driver: "none"
    build: 
      context: ../transaction-processor
      dockerfile: Dockerfile-api
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      VALIDATOR_URI: http://rest-api:8008
      MASTER_STATE_NAME: dev

  voting-frontend:
    build: ../front-end/dec-fr
    volumes:
      - built-frontend:/app/build
    depends_on:
      - voting-api
    environment:
      API_URL_INTERNAL: http://voting-api:8080
      REACT_APP_API_URL_EXTERNAL: http://localhost:8080
      INIT: 1
      PRODUCTION: 1

  voting-frontend-server:
    logging:
        driver: "none"
    image: nginx:alpine
    ports:
      - 80:80
    environment: 
      NGINX_PORT: 80
    volumes:
      - built-frontend:/usr/share/nginx/html:ro
      - ../front-end/dec-fr/scripts/nginx.conf:/etc/nginx/conf.d/default.conf:ro


  validator:
    logging:
      driver: "none"
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default
    expose:
      - 4004
    ports:
      - "4004:4004"
    # start the validator with an empty genesis batch
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawset proposal create \
          -k /root/.sawtooth/keys/my_key.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
        \""

  devmode-engine:
    logging:
      driver: "none"
    image: hyperledger/sawtooth-devmode-engine-rust:chime
    container_name: sawtooth-devmode-engine-rust-default
    depends_on:
      - validator
    entrypoint: devmode-engine-rust -C tcp://validator:5050

  rest-api:
    logging:
      driver: "none"
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-default
    ports:
      - "8008:8008"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:8008